# Generated by Django 2.0.4 on 2023-02-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20230131_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='カテゴリー名'),
        ),
    ]
