# Generated by Django 4.1 on 2023-02-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Folder', '0006_auto_20230203_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
