# Generated by Django 2.0.4 on 2023-02-03 03:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrUrl',
            fields=[
                ('tableNumber', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
